convert each #[test] in the futures-time files to a test-program and run it
i saw one flaky failure from debounce_no_debounces_hit

thread 'main' panicked at test-programs/src/bin/debounce_no_debounces_hit.rs:17:5:
assertion `left == right` failed
  left: 9
 right: 10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test debounce_no_debounces_hit ... FAILED
test http_first_byte_timeout ... ok
test tcp_echo_server ... ok
test throttle_smoke ... ok

failures:

---- debounce_no_debounces_hit stdout ----
testing /Users/pat/src/wstd/target/debug/build/test-programs-artifacts-208b828c32f0bad1/out/wasm32-wasip2/debug/debounce_no_debounces_hit.wasm
entering wasm...
Error: error while executing at wasm backtrace:
    0: 0x21b54 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!__rust_start_panic
    1: 0x219a2 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!rust_panic
    2: 0x218d0 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!std::panicking::rust_panic_with_hook::h6e665b71c8f50b27
    3: 0x20a0a - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!std::panicking::begin_panic_handler::{{closure}}::hb63ceb92de73cef0
    4: 0x20970 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!std::sys::backtrace::__rust_end_short_backtrace::hf18948010daec5d9
    5: 0x211ac - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!rust_begin_unwind
    6: 0x26754 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!core::panicking::panic_fmt::h7916dc01f99baff2
    7: 0x27d7d - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!core::panicking::assert_failed_inner::h636831bd2590e950
    8: 0x16ca1 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!core::panicking::assert_failed::h0b25b4e081d12bca
    9: 0x26b3 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!debounce_no_debounces_hit::main::__run::{{closure}}::hb8541acc2b0cb2ac
   10: 0x28ac - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!debounce_no_debounces_hit::main::{{closure}}::h254a3ed57087816f
   11: 0x2c2c - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!wstd::runtime::block_on::block_on::hb9ae51e568813b8f
   12: 0x132f - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!debounce_no_debounces_hit::main::h5e51c8cbf2739770
   13: 0x1fd4 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!core::ops::function::FnOnce::call_once::h755fe407d0481799
   14: 0x3457 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!std::sys::backtrace::__rust_begin_short_backtrace::h89d457ff90c86c52
   15: 0x33d0 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!std::rt::lang_start::{{closure}}::h062583bc0223ec5b
   16: 0x1fc6a - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!std::rt::lang_start_internal::h00f1a3877f58021e
   17: 0x336c - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!std::rt::lang_start::h365de7c23ff17921
   18: 0x1383 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!__main_void
   19: 0x1092 - debounce_no_debounces_hit-10b636a0d9796e1a.wasm!_start
   20: 0x4f31af - wit-component:adapter:wasi_snapshot_preview1!wasi:cli/run@0.2.0#run
note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information

Caused by:
    wasm trap: wasm `unreachable` instruction executed

failures:
    debounce_no_debounces_hit